#wait in seconds
wait=20
#base url
base.url=https://github.com/login
# Valid login
valid.username=GvantsaKi
valid.password=gvanciko970
#ExtentReportManager
report.environment=QA
report.tester=Gvantsa
report.name=Automation Test Report
report.title=Git Test Execution Report
#Profile Name for profile test
profile.name=GvantsaKi
